"""Detection signals for Provenance Guard.

Two genuinely distinct signals (planning.md §3):
  - Signal 1: Groq LLM classifier   -> semantic / holistic view
  - Signal 2: Stylometric heuristics -> structural / statistical view

Each returns an AI-likelihood in [0, 1] (1 = very AI-like).
"""

import json
import re
import statistics

import config

# --------------------------------------------------------------------------- #
# Signal 1 — Groq LLM classifier (semantic)
# --------------------------------------------------------------------------- #

_LLM_SYSTEM_PROMPT = (
    "You are an expert forensic linguist assessing whether a piece of text was "
    "written by a human or generated by an AI language model. Consider tone, "
    "voice, coherence, originality, hedging, and how 'generic' the prose feels. "
    "You must be cautious about false positives: authentic human writing can be "
    "formal, polished, or written by a non-native speaker. Respond ONLY with a "
    "JSON object of the form "
    '{"ai_probability": <float 0..1>, "reasoning": "<one short sentence>"}. '
    "ai_probability is your estimated probability the text is AI-generated: "
    "1.0 = certainly AI, 0.5 = genuinely cannot tell, 0.0 = certainly human."
)


def llm_signal(text):
    """Return (score, detail) where score is AI-likelihood in [0,1].

    On any failure (no key, API/network/parse error) returns (None, detail) so
    the caller can degrade gracefully to stylometry only (planning.md §4).
    """
    if not config.GROQ_API_KEY:
        return None, {"available": False, "error": "GROQ_API_KEY not set"}

    try:
        from groq import Groq

        client = Groq(api_key=config.GROQ_API_KEY)
        resp = client.chat.completions.create(
            model=config.GROQ_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _LLM_SYSTEM_PROMPT},
                {"role": "user", "content": f"Assess this text:\n\n{text}"},
            ],
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        score = float(data.get("ai_probability"))
        score = max(0.0, min(1.0, score))  # clamp
        return score, {
            "available": True,
            "reasoning": data.get("reasoning", ""),
            "model": config.GROQ_MODEL,
        }
    except Exception as exc:  # noqa: BLE001 - degrade gracefully on any error
        return None, {"available": False, "error": str(exc)}


# --------------------------------------------------------------------------- #
# Signal 2 — Stylometric heuristics (structural)
# --------------------------------------------------------------------------- #

# AI writing tends to over-use these connectors / hedges (planning.md §3).
_CLICHE_PHRASES = [
    "furthermore", "moreover", "in addition", "additionally", "however",
    "therefore", "consequently", "nevertheless", "nonetheless", "thus",
    "in conclusion", "to summarize", "in summary", "overall",
    "it is important to note", "it is worth noting", "it is essential",
    "it is crucial", "play a crucial role", "play a significant role",
    "a wide range of", "a variety of", "in today's", "in the realm of",
    "delve into", "navigate the", "landscape of", "paradigm shift",
    "stakeholders", "leverage", "foster", "underscore", "multifaceted",
    "ever-evolving", "rapidly changing", "transformative",
]

_WORD_RE = re.compile(r"[A-Za-z']+")


def _split_sentences(text):
    parts = re.split(r"[.!?]+", text)
    return [p.strip() for p in parts if p.strip()]


def _words(text):
    return _WORD_RE.findall(text.lower())


def _burstiness_score(sentences):
    """Low sentence-length variation -> AI-like. Returns AI-likelihood [0,1]."""
    lengths = [len(_words(s)) for s in sentences]
    lengths = [n for n in lengths if n > 0]
    if len(lengths) < 2:
        return 0.5  # not enough sentences to judge -> neutral
    mean = statistics.mean(lengths)
    if mean == 0:
        return 0.5
    cv = statistics.pstdev(lengths) / mean  # coefficient of variation
    # Human prose typically cv >= ~0.6 (bursty); AI often cv <= ~0.4 (uniform).
    # Map: cv >= 0.9 -> 0 (very human), cv = 0 -> 1 (very AI-like).
    ai = 1.0 - (cv / 0.9)
    return max(0.0, min(1.0, ai))


def _cliche_score(text, word_count):
    """Density of AI-favoured connectors/hedges -> AI-likelihood [0,1]."""
    if word_count == 0:
        return 0.5
    lowered = text.lower()
    hits = sum(lowered.count(p) for p in _CLICHE_PHRASES)
    per_100 = (hits / word_count) * 100
    # ~0 per 100 words -> human; >= ~3 per 100 words -> strongly AI-like.
    ai = per_100 / 3.0
    return max(0.0, min(1.0, ai))


def _sentence_length_score(sentences):
    """Longer, uniform sentences skew AI; short choppy ones skew human."""
    lengths = [len(_words(s)) for s in sentences]
    lengths = [n for n in lengths if n > 0]
    if not lengths:
        return 0.5
    avg = statistics.mean(lengths)
    # avg <= ~8 words -> human/casual (0); avg >= ~28 words -> AI-like (1).
    ai = (avg - 8.0) / (28.0 - 8.0)
    return max(0.0, min(1.0, ai))


def stylometric_signal(text):
    """Return (score, detail) where score is AI-likelihood in [0,1].

    Combines burstiness, cliché density, and average sentence length using the
    weights in config (planning.md §3, Signal 2).
    """
    sentences = _split_sentences(text)
    words = _words(text)
    word_count = len(words)
    unique_count = len(set(words))
    ttr = (unique_count / word_count) if word_count else 0.0

    burst = _burstiness_score(sentences)
    cliche = _cliche_score(text, word_count)
    sent_len = _sentence_length_score(sentences)

    score = (
        config.BURSTINESS_WEIGHT * burst
        + config.CLICHE_WEIGHT * cliche
        + config.SENTENCE_LENGTH_WEIGHT * sent_len
    )
    score = max(0.0, min(1.0, score))

    detail = {
        "available": True,
        "word_count": word_count,
        "sentence_count": len(sentences),
        "type_token_ratio": round(ttr, 3),
        "burstiness_ai": round(burst, 3),
        "cliche_ai": round(cliche, 3),
        "sentence_length_ai": round(sent_len, 3),
    }
    return score, detail


# --------------------------------------------------------------------------- #
# Signal 3 — Lexical redundancy (structural, but a distinct axis) [STRETCH: ensemble]
# --------------------------------------------------------------------------- #
# Measures how much the text REPEATS itself (phrasing reuse), independent of the
# LLM's semantics and stylometry's sentence shape. See planning.md §S1.

# Common words that shouldn't count toward "top-token dominance".
_STOPWORDS = {
    "the", "a", "an", "and", "or", "but", "of", "to", "in", "on", "for", "with",
    "is", "are", "was", "were", "be", "been", "it", "its", "this", "that", "as",
    "at", "by", "from", "i", "you", "he", "she", "they", "we", "my", "our",
}


def repetition_signal(text):
    """Return (score, detail) where score is AI-likelihood in [0,1].

    Blends distinct-bigram ratio (phrase variety) with top-token dominance
    (how much one word repeats). Low variety / high dominance -> more AI-like.
    """
    words = _words(text)
    n = len(words)
    if n < 4:
        return 0.5, {"available": True, "note": "too short for redundancy", "word_count": n}

    # distinct-bigram ratio: unique bigrams / total bigrams (1.0 = all unique)
    bigrams = [(words[i], words[i + 1]) for i in range(n - 1)]
    distinct2 = len(set(bigrams)) / len(bigrams)
    # Low distinct2 -> repetitive -> AI-like. Human casual prose ~0.95+.
    variety_ai = 1.0 - distinct2  # already in [0,1]

    # top-token dominance among content words
    content = [w for w in words if w not in _STOPWORDS]
    if content:
        counts = {}
        for w in content:
            counts[w] = counts.get(w, 0) + 1
        top = max(counts.values())
        dominance = top / len(content)
    else:
        dominance = 0.0
    # ~0.03 dominance -> human; >= ~0.12 -> strongly repetitive.
    dominance_ai = max(0.0, min(1.0, (dominance - 0.03) / (0.12 - 0.03)))

    score = 0.6 * variety_ai + 0.4 * dominance_ai
    score = max(0.0, min(1.0, score))

    detail = {
        "available": True,
        "word_count": n,
        "distinct_bigram_ratio": round(distinct2, 3),
        "top_token_dominance": round(dominance, 3),
        "variety_ai": round(variety_ai, 3),
        "dominance_ai": round(dominance_ai, 3),
    }
    return score, detail


# --------------------------------------------------------------------------- #
# STRETCH S4 — Multi-modal: image-metadata provenance check
# --------------------------------------------------------------------------- #
# Hard provenance (declared generator software / C2PA-style fields) beats soft
# statistical inference. See planning.md §S4.

_AI_GENERATOR_MARKERS = [
    "midjourney", "dall-e", "dall e", "dalle", "stable diffusion", "sdxl",
    "firefly", "imagen", "flux", "leonardo", "ideogram", "gan", "gpt",
    "generated by ai", "text-to-image",
]


def metadata_provenance_check(metadata):
    """Scan image metadata for authoritative AI-generation markers.

    Returns {"declared_ai": bool, "evidence": [...], "fields_checked": int}.
    """
    if not isinstance(metadata, dict):
        return {"declared_ai": False, "evidence": [], "fields_checked": 0}

    evidence = []

    # Explicit boolean / C2PA-style declarations.
    for key in ("ai_generated", "is_ai_generated", "synthetic"):
        if str(metadata.get(key)).lower() in ("true", "1", "yes"):
            evidence.append(f"{key}={metadata.get(key)}")
    dst = str(metadata.get("digital_source_type", "")).lower()
    if "trainedalgorithmicmedia" in dst or "compositewithtrainedalgorithmic" in dst:
        evidence.append(f"digital_source_type={metadata.get('digital_source_type')}")

    # Software / tool / model name markers.
    for key in ("software", "tool", "model", "generator", "creator_tool", "engine"):
        val = str(metadata.get(key, "")).lower()
        for marker in _AI_GENERATOR_MARKERS:
            if marker in val:
                evidence.append(f"{key}='{metadata.get(key)}' matches '{marker}'")
                break

    return {
        "declared_ai": len(evidence) > 0,
        "evidence": evidence,
        "fields_checked": len(metadata),
    }
